package com.iss.saas.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-03-31T21:56:11.006+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://server.saas.iss.com", name = "SaaS2AppService")
@XmlSeeAlso({ObjectFactory.class})
public interface SaaS2AppService {

    @WebMethod
    @RequestWrapper(localName = "execute", targetNamespace = "http://server.saas.iss.com", className = "com.iss.saas.server.Execute")
    @ResponseWrapper(localName = "executeResponse", targetNamespace = "http://server.saas.iss.com", className = "com.iss.saas.server.ExecuteResponse")
    @WebResult(name = "executeReturn", targetNamespace = "http://server.saas.iss.com")
    public String execute(
            @WebParam(name = "requestXML", targetNamespace = "http://server.saas.iss.com")
            String requestXML
    );
}
